name: hello-workflow
on:
  issues:
    types: [opened]

    - uses: actions/github-script@v7
    id: my-script
    with:
      result-encoding: string
      retries: 3
      script: |
        github.rest.issues.get({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
        })
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}